import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { AbapRoutine, Node } from '../types';
import { Bot, Code2, ArrowRight, Loader2, CheckCircle, Zap } from 'lucide-react';

interface CodeConverterProps {
  node: Node;
  routine?: AbapRoutine;
  onConvert: (nodeId: string, abapCode: string) => Promise<void>;
  onDeploy: (nodeId: string) => Promise<void>;
}

export function CodeConverter({ node, routine, onConvert, onDeploy }: CodeConverterProps) {
  const [isConverting, setIsConverting] = useState(false);
  const [isDeploying, setIsDeploying] = useState(false);

  const handleConvert = async () => {
    if (!routine?.abap_code) return;
    setIsConverting(true);
    await onConvert(node.id, routine.abap_code);
    setIsConverting(false);
  };

  const handleDeploy = async () => {
    setIsDeploying(true);
    await onDeploy(node.id);
    setIsDeploying(false);
  };

  if (!routine) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-slate-400 p-8 text-center">
        <Code2 size={48} className="mb-4 opacity-50" />
        <p>No ABAP transformation routines found for this object.</p>
        <p className="text-sm mt-2">This object might be a direct pass-through or a source system table.</p>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col gap-4 p-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          <Bot className="text-purple-500" />
          The Brain: AI Conversion
        </h3>
        <div className="flex gap-2">
          <button
            onClick={handleConvert}
            disabled={isConverting || routine.status === 'CONVERTED'}
            className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isConverting ? <Loader2 className="animate-spin" size={16} /> : <Zap size={16} />}
            {routine.status === 'CONVERTED' ? 'Re-Convert' : 'Convert to SQL'}
          </button>
          
          {routine.status === 'CONVERTED' && (
            <button
              onClick={handleDeploy}
              disabled={isDeploying || node.deployment_status === 'DEPLOYED'}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 transition-colors"
            >
              {isDeploying ? <Loader2 className="animate-spin" size={16} /> : <CheckCircle size={16} />}
              {node.deployment_status === 'DEPLOYED' ? 'Deployed' : 'Deploy'}
            </button>
          )}
        </div>
      </div>

      <div className="flex-1 grid grid-cols-2 gap-4 min-h-0">
        <div className="flex flex-col gap-2 min-h-0">
          <div className="text-sm font-medium text-slate-500 flex justify-between">
            <span>Source: ABAP ({routine.routine_type})</span>
          </div>
          <div className="flex-1 bg-slate-900 rounded-lg p-4 overflow-auto font-mono text-sm text-slate-300 border border-slate-700">
            <pre>{routine.abap_code}</pre>
          </div>
        </div>

        <div className="flex flex-col gap-2 min-h-0">
          <div className="text-sm font-medium text-slate-500 flex justify-between">
            <span>Target: BigQuery SQL</span>
            {routine.converted_sql && <span className="text-green-600 text-xs bg-green-100 px-2 py-0.5 rounded-full">Generated by Gemini 1.5 Pro</span>}
          </div>
          <div className="flex-1 bg-slate-50 rounded-lg p-4 overflow-auto font-mono text-sm text-slate-800 border border-slate-200 shadow-inner relative">
            {routine.converted_sql ? (
              <motion.pre
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
              >
                {routine.converted_sql}
              </motion.pre>
            ) : (
              <div className="h-full flex items-center justify-center text-slate-400 italic">
                Waiting for conversion...
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}


